### ISSUE TITLE
Allow mentioned replies to be counted as ping notifications

### ISSUE THREAD

**Issue by lewisakura** [BenSegal855/In-app-notifs#17]
Currently, all notifications that are not pings are ignored if you have only pings enabled:
https://github.com/BenSegal855/In-app-notifs/blob/2607b3d4ff03043d851be576064f941ccb47949e/index.js#L39-L40
However, replies are also ignored, which do trigger a ping to the user. It would be nice if there was a way to allow a mention reply to also trigger a notification.

The way I would do it would be to work out if the `referenced_message` is a message you sent, then check if the message's `allowed_mentions` property has `replied_user` (if I remember correctly) to true, although I'm not sure how to get a message from a message ID in Powercord.

**Comment by BenSegal855** [comment]
Getting a message by ID is harder than it sounds since there is a good chance the message wont be cached. However, The message object does have a handy `mentions` array that does contain the user on a reply ping. Ill add this soon.

**Comment by BenSegal855** [comment]
Added in 0.4.2
