### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by SheepCommander** [BenSegal855/In-app-notifs#20]

**Comment by BenSegal855** [comment]
Cannot reproduce, please provide the plugin version, powercord version, discord version and any errors related to the plugin.

**Comment by SheepCommander** [comment]
Huh can you send a screenshot of it working? I'll work on recording a video of it not working

Anyways I am ofc on discord canary with powercord plugged, here's picture of the plugin card

![image](https://user-images.githubusercontent.com/66646514/144725221-83f68384-3ae2-4966-b9ea-a7f188da843a.png)

**Comment by SheepCommander** [comment]
https://user-images.githubusercontent.com/66646514/144725278-c9b66140-68bf-4c4a-91f6-a9bd338eceaa.mp4

**Comment by SheepCommander** [comment]
**List of Installed Plugins (80)**
```pc-commands
pc-settings
pc-moduleManager
pc-updater
AFK-on-exit
background-player
badges-everywhere
bdCompat
better-folders
better-settings
better-status-indicators
betterInvites
copy-avatar-url
copy-raw-message
copy-role-color
copy-server-icon
css-toggler
custom-rpc
custom-timestamps
Custom-Volume-Range
discord-status
DM-Typing-Indicator
fix-user-popouts
github-in-discord
guild-profile
image-to-clipboard
In-app-notifs
inbox-unread-count
kaomoji
Link-Preview-Utility
message-link-embed
notey
Open-Folder
pc-connections
pc-docs
pc-rpc
pc-sdk
pc-stafftags
permission-viewer
petpet
PowerAliases
powercord-custom-apps
powercord-duckduckgo
powercord-fumo-api
powercord-greentext
powercord-message-hider
powercord-reverse-image-search
powercord-sauce
PowercordModuleFinder
PowercordPluginDownloader
PowercordReacter
PowerFiles
preview-hider
reddit-parser
Rejoin-VC
reload-from-tray
remind-me
remove-invite-from-user-context-menu
report-messages
rolecolor-everywhere
scrollable-autocomplete
Send-Message-with-Webhook
shake
share-plugins
show-all-activities
show-sessions
smart-typers
StreamerModeOnGoLive
text-react
time-in-pc
token
total-members
twemoji-but-good
Unindent
upload-from-links
userid-info
userNotifs
vcTimer
virus-checker
vpc-shiki

**Comment by BenSegal855** [comment]
Notifications usually dont go through if your in streamer mode so try it again without being in streamer mode. Also, double check your settings to ensure something like `Only notify on ping` is disabled. If the issue still persists, please share your powercord version, which can be found in the updater settings tab, and your discord version, which can be found at the bottom of the lettings list.

**Comment by SheepCommander** [comment]
https://user-images.githubusercontent.com/66646514/144730125-f7eb181e-c159-40e7-ac09-0af316ae4022.mp4

**Comment by BenSegal855** [comment]
If you're trying to show me that IAN isnt sending a notification when you try to install it then you should know that IAN doesnt send those notifications. Make sure you have pc-notices enabled and then try it again. **IF THAT DOESNT WORK THEN SEND YOUR POWERCORD VERSION AND DISCORD VERSION, NOT ANOTHER VIDEO WITH NO EXPLINATION OF WHAT YOU ARE TRYING TO SHOW ME**

**Comment by SheepCommander** [comment]
Ah PC-Notices got disabled somehow. Also other than Discord Canary and this

![image](https://user-images.githubusercontent.com/66646514/144736160-706d18c9-1b27-40ac-8966-08a39e9796b6.png)

I'm not sure what you mean by powercord version & discord version
